application: gift-tracker
version: 1
runtime: python
api_version: 1


handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /_ah/queue/deferred
  script: $PYTHON_LIB/google/appengine/ext/deferred/handler.py
  login: admin

- url: /favicon.ico
  static_files: gift-tracker/static/media/favicon.ico
  upload: gift-tracker/static/media/favicon.ico

- url: /css
  static_dir: gift-tracker/static/media/css

- url: .*
  script: main.py
